import { useCallback, useEffect, useState } from 'react';
import { supabase } from '../lib/supabase';
import { useCheckInStorage } from './useStorage';
import { Deck, Question } from '../shared/types';
import NetInfo, { NetInfoState } from '@react-native-community/netinfo';
import AsyncStorage from '@react-native-async-storage/async-storage';
import { Session } from '@supabase/supabase-js';

export function useSupabase() {
  const [session, setSession] = useState<Session | null>(null);
  const [loadingSession, setLoadingSession] = useState(true);
  const [activeDeck, setActiveDeck] = useState<{ deck: Deck; questions: Question[] } | null>(null);
  const [loadingDeck, setLoadingDeck] = useState(false);
  const [syncing, setSyncing] = useState(false);

  // Auth state listener
  useEffect(() => {
    supabase.auth.getSession().then(({ data: { session } }) => {
      setSession(session as any);
      if (session) fetchActiveDeck();
      setLoadingSession(false);
    });

    const { data: { subscription } } = supabase.auth.onAuthStateChange((_event, session) => {
      setSession(session as any);
      if (session) fetchActiveDeck();
      else setActiveDeck(null);
      setLoadingSession(false);
    });

    return () => subscription.unsubscribe();
  }, []);

  // Offline Sync Listener
  useEffect(() => {
    const unsubscribe = NetInfo.addEventListener((state: NetInfoState) => {
      if (state.isConnected && session) {
        syncPendingResponses();
      }
    });
    return unsubscribe;
  }, [session]);

  const pairWithDoctor = async (pairingCode: string) => {
    const code = pairingCode.toUpperCase().trim();
    // We use a deterministic email/password generated by the doctor dashboard to sign in securely
    const { data, error } = await supabase.auth.signInWithPassword({
      email: `${code}@penguinpals.health`,
      password: `${code}-securepass123`,
    });

    if (error) {
      console.error('Pairing failed:', error.message);
      throw new Error('Invalid pairing code. Please check with your doctor.');
    }
    
    // Check if the pairing code is expired
    const { data: patient } = await supabase
      .from('patients')
      .select('*')
      .eq('id', data.user.id)
      .single();

    if (patient && new Date(patient.pairing_code_expires_at) < new Date()) {
      await supabase.auth.signOut();
      throw new Error('This pairing code has expired.');
    }

    return true;
  };

  const fetchActiveDeck = useCallback(async () => {
    setLoadingDeck(true);
    try {
      // Fetch active deck for this patient
      const { data: decks, error: deckError } = await supabase
        .from('decks')
        .select('*')
        .eq('status', 'active');

      if (deckError || !decks || decks.length === 0) {
        setActiveDeck(null);
        return;
      }

      const deck = decks[0] as Deck;

      // Fetch questions for this deck
      const { data: questions, error: qError } = await supabase
        .from('questions')
        .select('*')
        .eq('deck_id', deck.id)
        .order('order', { ascending: true });

      if (qError) throw qError;

      setActiveDeck({ deck, questions: questions as Question[] });
    } catch (e) {
      console.error('Error fetching deck:', e);
      setActiveDeck(null); // Fallback to offline/empty
    } finally {
      setLoadingDeck(false);
    }
  }, [session]);

  // Queue response for offline-first sync
  const submitResponse = async (questionId: string, value: any, skipped: boolean, sessionId: string) => {
    if (!activeDeck || !session) return;

    const payload = {
      question_id: questionId,
      patient_id: session.user.id,
      deck_id: activeDeck.deck.id,
      session_id: sessionId,
      value,
      skipped,
      answered_at: new Date().toISOString()
    };

    // Always cache locally first
    const Q_KEY = '@penguinpals:pending_responses';
    const pending = JSON.parse((await AsyncStorage.getItem(Q_KEY)) || '[]');
    pending.push(payload);
    await AsyncStorage.setItem(Q_KEY, JSON.stringify(pending));

    // Try background sync immediately
    syncPendingResponses();
  };

  // Sync queued responses to Supabase
  const syncPendingResponses = async () => {
    if (syncing) return;
    setSyncing(true);

    const Q_KEY = '@penguinpals:pending_responses';
    try {
      const pending: any[] = JSON.parse((await AsyncStorage.getItem(Q_KEY)) || '[]');
      if (pending.length === 0) return;

      const { error } = await supabase.from('responses').insert(pending);
      
      if (!error) {
        // Success - clear queue
        await AsyncStorage.removeItem(Q_KEY);
      } else {
        console.error('Sync error:', error.message);
      }
    } catch (e) {
      console.error('Offline sync failed', e);
    } finally {
      setSyncing(false);
    }
  };

  const createCheckInSession = async (totalQuestions: number) => {
    if (!activeDeck || !session) return 'offline-session-id';
    
    // In a real robust offline system, we'd also queue session creation.
    // For simplicity, if online we create it.
    const { data } = await supabase.from('check_in_sessions').insert([{
      patient_id: session.user.id,
      deck_id: activeDeck.deck.id,
      questions_total: totalQuestions,
      questions_answered: 0
    }]).select('id').single();

    return data?.id || 'offline-session-id';
  };

  return {
    session,
    loadingSession,
    pairWithDoctor,
    activeDeck,
    loadingDeck,
    submitResponse,
    createCheckInSession,
    refreshDeck: fetchActiveDeck
  };
}
